apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-main
  namespace: prod-main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: ubuntu
        ports:
        - containerPort: 80
